# Generated by Django 3.1.7 on 2021-03-19 10:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptravel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('photo', models.ImageField(upload_to='posts/', verbose_name='Фото')),
                ('data_create', models.DateField(default=datetime.date(2021, 3, 19), verbose_name='Дата создания')),
                ('text', models.CharField(max_length=3000, verbose_name='Описание')),
                ('count_likes', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('id_traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_create', models.DateField(default=datetime.date(2021, 3, 19), verbose_name='Дата создания')),
                ('text', models.CharField(max_length=1500, verbose_name='Описание')),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptravel.post')),
                ('id_traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
